In [79]:
# assignment
# =================

# 1. create a program that displays a multiplication table
# eg. 2 x 1 = 2
#     2 x 2 = 4
# up to 2 x 12 = 24

# NB: Do not write out the table one by one. Use loop.

# the number = 2
# pick the number, add multiplication sign
# add number that increases by one
# add equality sign
# multiple the number by the increase value

# x = 2
# num = 1
# while num <= 12:
#     print(f"{x} x {num} = {x * num}")
# #     print(x, "x", num, "=", x * num)
#     num = num + 1


# 2. create a program that finds the largest of 3 numbers
a = 14
b = 50
c = 50
#pick first number and check if it is bigger than 2nd and 3rd number
# if true, first number is the biggest
# if 2nd number is greater than first and third number, second number is the largest
# otherwise 3rd number will be the largest

# if a > b and a > c:
#     print(a, "is the largest")
# elif b > a and b > c:
#     print(b,"is the largest")
# elif c > b and c > a:
#     print(c, "is the largest")
# else:
#     print("No largest among the 3 numbers")

# pick first number and compare to second number
# the one that is largest among them, compare to next number
# if the same number is bigger, it remains the largest
# continue to the end

# data = [100,2,40,56, 20, 40, 10]
# largest = data[0]
# for i in data:
#     if i > largest:
#         largest = i
# print(largest)   



# 3.  create a program that take a score and show the grade using if else or match case:
# 90 - 100 ("Grade A")
# 70 - 89  ("Grade B")
# 50 - 69 ("Grade C")
# 30 - 49 ("Grade D")
# 0 - 29  ("Grade E")

# score = 99.8
# if score >= 90 and score <= 100:
#     print("Grade A")
# elif score >= 70:
#     print("Grade B")
# elif score >= 50:
#     print("Grade C")
# elif score >= 30:
#     print("Grade D")
# elif score >= 0:
#     print("Grade E")
# else:
#     print("Invalid score")

# score = 30
# match(score):
#     case ((score >= 90) and (score <= 100)):
#         print("Grade A")
#     case score >= 70:
#         print("Grade B")
#     case score >= 50:
#         print("Grade C")
#     case score >= 30:
#         print("Grade D")
#     case score >= 0:
#         print("Grade E")
#     case _:
#         print("Invalid grade")

# print(score >= 90)

# so if I enter any number as score it show the corresponding grade

# 3. Create a program that accepts 2 numbers and an operator eg. 5 6, +
# then perform an operation based on what the user enters eg 5 + 6
# if the user enters 2, 8, * it should return 2 * 8
# and show the answer in console

# num1 = int(input("Enter first number"))
# operator = input("Enter an operator eg. +, -, /, *")
# num2 = int(input("Enter second number"))
# if operator == "+":
#     print(num1 + num2)
# elif operator == "-":
#     print(num1 - num2)
# elif operator == "/":
#     if num1 > num2:
#         print(num1 / num2)
#     else:
#         print(num2 / num1)
# elif operator == "*":
#     print(num1 * num2)
# else:
#     print("Invalid operator")

# 4. create a program that removes a duplicate from an array
# eg. 
numbers = [2,1,3,1,4,6,1,8,2,1,3,4,1,1,1,1,1,1,1,1]
# print(set(numbers))

# basket = []
# for i in numbers:
#     if i not in basket:
#         basket.append(i)
        
# print(basket)


# 5. create a program that checks if a word is palindrome
# ie. it is the same when you spell it backward
# eg. madam, eye

# word = "wale"
# reversed_word = word[::-1]
# if word == reversed_word:
#     print("It is palindrome")
# else:
#     print("not palindrome")

score = 10
match score:
    case 90 <= score <= 100:
        "Grade A"
    case 70 <= score < 90:
        "Grade B"
    case 50 <= score < 70:
        "Grade C"
    case 30 <= score < 50:
        "Grade D"
    case 0 <= score < 30:
        "Grade E"
    case _:
        "Invalid Score"

SyntaxError: invalid syntax (2668156874.py, line 145)

In [49]:
# Function - is a block of code that can be reused

def add_numbers():
    return 2 + 2

In [50]:
add_numbers()

4

In [51]:
add_numbers()

4

In [52]:
# function parameter
def add_numbers(x,y):
    return x + y

In [54]:
add_numbers(4,6)

10

In [55]:
add_numbers(3,2)

5

In [56]:
def check_palindrone(word):
    reversed_word = word[::-1]
    if word == reversed_word:
        print("It is palindrome")
    else:
        print("not palindrome")

In [58]:
check_palindrone("malam")

It is palindrome


In [59]:
check_palindrone("int")

not palindrome


In [60]:
check_palindrone("ada")

It is palindrome


In [ ]:
# lambda - anonymous function
def add_numbers(x,y):
    return x + y

In [ ]:
lambda x, y: x + y

In [65]:
# module - modules is the process of importing code that are written someone and use it in your code

import calculate
calculate.add_it(2,3)

5

In [67]:
from calculate import sub_it, add_it
sub_it(8,4)

4

In [69]:
# writing a file
file = open("newpythonclass.txt", "w")
file.write("This is magical")

15

In [71]:
# ls

In [72]:
# Reading file
file = open("newpythonclass.txt", "r")
file.read()

'This is magical'

In [73]:
file = open("newpythonclass.txt", "w")
file.write("Life is not hard")

16

In [74]:
file = open("newpythonclass.txt", "r")
file.read()

'Life is not hard'

In [75]:
file = open("newpythonclass.txt", "a")
file.write("\nThis is interesting")

20

In [77]:
file = open("newpythonclass.txt", "r")
file.read()

'Life is not hard\nThis is interesting'

In [80]:
# Numpy is a python library for generating sample data and working with multi dimensional arrays

In [90]:
one = [1,2,3,5]
two = [2,3,4,5]
one + two

[1, 2, 3, 5, 2, 3, 4, 5]

In [91]:
# bring in numpy library into our notebook
import numpy as np

In [92]:
# converting data into numpy array
np.array(one) + np.array(two)

array([ 3,  5,  7, 10])

In [85]:
# generate sample data
np.arange(5)

array([0, 1, 2, 3, 4])

In [87]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [97]:
matrix = [[1,2,3],[4,5,6],[4,4,5]]

In [100]:
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 5]])

In [101]:
# numpy array properties
matrix.shape

(3, 3)

In [107]:
matrix.ndim

2

In [108]:
matrix.dtype

dtype('int32')

In [109]:
matrix.size

9

In [110]:
x = np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [111]:
x.ndim

1

In [116]:
x.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [106]:
# generate random data
# rand generate random number between 0 and 1
np.random.rand(4,2)

array([[0.88870364, 0.20812748],
       [0.77432052, 0.90713851],
       [0.59828265, 0.86894798],
       [0.95070547, 0.00570189]])

In [119]:
# randn can generate floatinmg values below 0 and above 1
np.random.randn(10,5)

array([[-0.17842002,  0.32361558, -1.2403744 ,  0.69551644,  0.61106782],
       [ 0.85101722, -0.64447033, -1.60127051,  0.0949665 , -0.53785159],
       [-1.73094247,  0.97355229,  0.823115  ,  0.14291638, -0.03478239],
       [ 2.33189389,  1.97554026,  0.59710056,  0.96705675,  1.74842683],
       [-1.1691029 , -0.72099581, -0.73176191,  0.60170185, -1.75737386],
       [ 0.52287205,  0.65297811, -0.05911608, -1.81015078, -0.62623475],
       [ 0.98145391,  0.93595929, -0.01452716, -1.24615775, -0.80563686],
       [-2.5009588 ,  1.30999154,  0.11206878,  0.68282413,  1.79086853],
       [ 0.76094343, -0.99694205,  0.51576675, -0.9785747 , -0.25018804],
       [ 0.11604543,  1.31542827,  0.53423288,  0.47580837, -0.80037067]])

In [123]:
np.random.randint(5)

2

In [125]:
# randint will generate random integeter between the interval specified
# the last digit (third) means number of items to generate
np.random.randint(2,21,3)

array([13, 10,  2])

In [127]:
# used to generate evenly spaced floating numbers
np.linspace(1,11)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [129]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [130]:
# broadcasting

np.array([1,2,3,4]) + np.array([6,5,5,4])

array([7, 7, 8, 8])

In [131]:
np.array([1,2,3,4]) + np.array([6])

array([ 7,  8,  9, 10])

In [140]:
a = np.array([[1,2,3],[4,5,6],[2,2,3]])
b = np.array([1,2,3])

In [141]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [142]:
a + b

array([[2, 4, 6],
       [5, 7, 9],
       [3, 4, 6]])

In [143]:
# indexing and slicing of numpy
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [149]:
a[1][1]

5

In [150]:
a[2][2]

3

In [151]:
a[0][1]

2

In [152]:
# slicing 
a[1:3,0:2]

array([[4, 5],
       [2, 2]])

In [153]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [158]:
a[0:3,1:2]

array([[2],
       [5],
       [2]])

In [157]:
a[2:3,0:3]

array([[2, 2, 3]])

In [162]:
# suming the columns (axis 0 = column)
a.sum(axis=0)

array([ 7,  9, 12])

In [163]:
# (axis 1 = row)
a.sum(axis=1)

array([ 6, 15,  7])

In [164]:
a.sum()

28

In [168]:
#summing only one column
a.sum(axis=0)[2]

12

In [170]:
#filtering data
a[a > 4]

array([5, 6])